//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagueVeloz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORNECEDOR()
        {
            this.TELEFONE = new HashSet<TELEFONE>();
        }
    
        public int FND_Id { get; set; }
        public int EMP_Id { get; set; }
        public string FND_Nome { get; set; }
        public string FND_TipoPessoa { get; set; }
        public string FND_Documento { get; set; }
        public string FND_RG { get; set; }
        public Nullable<System.DateTime> FND_DataNascimento { get; set; }
        public Nullable<System.DateTime> FND_DataCadastro { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEFONE> TELEFONE { get; set; }
    }
}
